___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.2

#### Мета: 

* навчитися працювати із бібліотекою Pandas в Python.

### Завдання:

In [1]:
import pandas as pd
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [2]:
pd.__version__

'0.25.1'

In [3]:
df = pd.read_csv(r'C:\Users\Аня\Desktop\DS_7\Lab 5\Ecommerce Purchases.csv')

Скільки рядків і стовпців в наборі даних:

In [4]:
df = pd.DataFrame(df)
shape = df.shape
print("rows: ", shape[0] )
print("columns: ", shape[1] )

rows:  10000
columns:  14

Перевірити, чи в наборі даних містяться порожні значення:

In [5]:
df.isnull().sum()

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            0
Purchase Price      0
dtype: int64

Яка середня ціна закупки (Purchase Price):

In [6]:
print("Середня ціна закупки: ", df["Purchase Price"].mean())

Середня ціна закупки:  50.34730200000025

Скільки людей користуються англійською мовою "en" на веб-сайті:

In [7]:
lg = df['Language']
print('Кількість людей користуються англійською мовою: ', lg[lg == "en"].count())

Кількість людей користуються англійською мовою:  1098

Скільки людей має посаду «Lawyer»?

In [8]:
job = df['Job']
print('Посада Lawyer: ', job[job == "Lawyer"].count())

Посада Lawyer:  30

Скільки людей зробило покупку вранці та скільки людей зробило покупку після обіду?

In [9]:
day_pr = df['AM or PM']
print('AM: ', day_pr[day_pr == "AM"].count())
print('PM: ', day_pr[day_pr == "PM"].count())

AM:  4932
PM:  5068

Які 5 найпоширеніших назв вакансій?

In [10]:
df['Job'].value_counts().head()

Interior and spatial designer        31
Lawyer                               30
Social researcher                    28
Research officer, political party    27
Designer, jewellery                  27
Name: Job, dtype: int64

Хтось здійснив покупку, яка надійшла від Lot: "90 Wt", та якою була ціна придбання для цієї транзакції?

In [11]:
lot_90WT = df[df['Lot'] == "90 WT"]

print("Здійснила покупку компанія ", lot_90WT['Company'][513])
print("Ціна: ", lot_90WT['Purchase Price'][513])

Здійснила покупку компанія  Bright PLC
Ціна:  75.1

Яка електронна адреса особи з таким номером кредитної картки: 4926535242672853 ?

In [12]:
df[df['Credit Card'] == 4926535242672853]['Email'][1234]

'bondellen@williams-garza.com'

Скільки людей використовує American Express  і здійснили покупку на суму понад 100 доларів?

In [13]:
#There is noone who has purchase which costs over 100$
num = df[df['Purchase Price'] > 90]['CC Provider'][df['CC Provider'] == 'American Express'].count()
print('Використовують American Express і здійснили покупку на суму понад 90 доларів:', num)

Використовують American Express і здійснили покупку на суму понад 90 доларів: 86

Скільки людей мають кредитну картку, термін дії якої закінчується в 2025 році?

In [14]:
num = df['CC Exp Date'].map(lambda x: '25' in x).sum()
print('Кількість людей мають кредитну картку, термін дії якої закінчується в 2025 році: ', num )

Кількість людей мають кредитну картку, термін дії якої закінчується в 2025 році:  1033

Які найкращі 5 найпопулярніших постачальників / хостів електронної пошти (наприклад, gmail.com, yahoo.com тощо ...).

In [15]:
print('5 найпопулярніших постачальників / хостів електронної пошти: ')
df['Email'].map(lambda x: x.split('@')[1]).value_counts().head()

5 найпопулярніших постачальників / хостів електронної пошти:

hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: Email, dtype: int64

Виведіть зведену таблицю по браузерах(Browser Info), посаді(Job), та кількості транзакцій :

In [16]:
new_df = df.groupby( ['Browser Info', 'Job'])['Credit Card'].agg( {'Credit Card': ['value_counts', ]})
new_df

C:\anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version. Use                 named aggregation instead.

    >>> grouper.agg(name_1=func_1, name_2=func_2)

  """Entry point for launching an IPython kernel.

                                                                                                           Credit Card
                                                                                                          value_counts
Browser Info                                       Job                                   Credit Card
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_0 r... Psychotherapist, dance movement       343076140197639             1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_0 r... Retail merchandiser                   3096254252496874            1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_0 r... Firefighter                           869916653863099             1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_0 r... Broadcast presenter                   4131734943433               1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_0) ... Development worker, international aid 6011186377707444            1
...                                                                                                                ...
Opera/9.99.(X11; Linux i686; sl-SI) Presto/2.9.... Company secretary                     869996965912834             1
Opera/9.99.(X11; Linux x86_64; en-US) Presto/2.... Dramatherapist                        6011927695764173            1
Opera/9.99.(X11; Linux x86_64; en-US) Presto/2.... Private music teacher                 6011834084089305            1
Opera/9.99.(X11; Linux x86_64; it-IT) Presto/2.... Hotel manager                         343654787368620             1
Opera/9.99.(X11; Linux x86_64; it-IT) Presto/2.... Scientist, forensic                   5570452384617561            1

[10000 rows x 1 columns]

Створіть нову колонку "Actual price", яка утворюється із "Purchase Price" та націнки за принципом:
- якщо "Purchase Price" > 50, націнка 20%
- якщо "Purchase Price" > 100, націнка 10%
- в інших випадках націнка 30%

In [17]:
def ac_price(price):
    if price < 50:
        return price*1.3
    elif price < 90:
        return price*1.2
    else:
        return price*1.1
df['Actual price'] = df['Purchase Price'].map(ac_price)
df

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price,Actual price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14,107.954
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73,84.876
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95,1.235
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04,93.648
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82,93.384
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21,98.652
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63,33.319
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98,100.776
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84,50.492
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59,81.108

Зробіть рангування набору даних по "Language" та "Actual price" в порядку спадання ціни.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rank.html

In [18]:
df_r = df[['Language', 'Actual price']].rank()
df_r['Actual price'].sort_values(ascending = False)

7807    9999.5
2092    9999.5
9856    9998.0
7604    9997.0
3844    9996.0
         ...
2783       4.5
8656       4.5
6863       3.0
2876       1.5
5487       1.5
Name: Actual price, Length: 10000, dtype: float64

Колонку "Language" (категоріальна змінна) "закодуйте", тобто утворити індикаторні колоник. В наборі не повинна залишитися колонка "Language".

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rank.html

In [20]:
df['Language'] = df['Language'].astype("category")
df['encoded_lg'] = df['Language'].cat.codes
df1 = df.drop(columns = 'Language')
df1

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Purchase Price,Actual price,encoded_lg
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,98.14,107.954,1
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,70.73,84.876,4
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,0.95,1.235,0
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,78.04,93.648,3
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,77.82,93.384,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,82.21,98.652,5
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,25.63,33.319,6
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,83.98,100.776,1
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,38.84,50.492,3
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,67.59,81.108,1

Кінцевий набір даних збережіть у файл з розширенням csv.

In [27]:
df1.to_csv('5.2result')

In [28]:
df_res = pd.read_csv(r'C:\Users\Аня\Desktop\DS_7\Lab 5\5.2result')
df_res

,Unnamed: 0,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Purchase Price,Actual price,encoded_lg
0,0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,98.14,107.954,1
1,1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,70.73,84.876,4
2,2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,0.95,1.235,0
3,3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,78.04,93.648,3
4,4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,77.82,93.384,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,342945015358701,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,82.21,98.652,5
9996,9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",210033169205009,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,25.63,33.319,6
9997,9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6011539787356311,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,83.98,100.776,1
9998,9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,180003348082930,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,38.84,50.492,3
9999,9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4139972901927273,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,67.59,81.108,1